{{ if eq .Values.cluster.name "master" }}
{{ if .Values.github.enabled }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: infrabox-github
    namespace: {{ template "system_namespace" . }}
    labels:
        app: infrabox-github
spec:
    replicas: 1
    template:
        metadata:
            labels:
                app: infrabox-github
        spec:
            containers:
            {{ include "containers_database" . | indent 12 }}
            -
                name: github-trigger
                image: {{ include "image_repository" . }}/gihub-trigger:{{ include "image_tag"  . }}
                imagePullPolicy: Always
                env:
                {{ include "env_database" . | indent 16 }}
                {{ include "env_github" . | indent 16 }}
                {{ include "env_general" . | indent 16 }}
                {{ include "env_github_secrets" . | indent 16 }}
                {{ include "env_version" . | indent 16 }}
                resources:
                    requests:
                        memory: "256Mi"
                        cpu: "200m"
            -
                name: github-review
                image: {{ include "image_repository" . }}/gihub-review:{{ include "image_tag"  . }}
                imagePullPolicy: Always
                env:
                {{ include "env_database" . | indent 16 }}
                {{ include "env_github" . | indent 16 }}
                {{ include "env_general" . | indent 16 }}
                {{ include "env_version" . | indent 16 }}
                resources:
                    requests:
                        memory: "256Mi"
                        cpu: "200m"
            volumes:
                {{ include "volumes_database" . | indent 16 }}
{{ end }}
{{ end }}
