apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: infrabox-scheduler
    namespace: {{ template "system_namespace" . }}
    labels:
        app: infrabox-scheduler
spec:
    replicas: 1
    template:
        metadata:
            annotations:
                checksum/config: {{ (.Files.Glob "config/docker/*").AsConfig | sha256sum }}
            labels:
                app: infrabox-scheduler
        spec:
            terminationGracePeriodSeconds: 0
            {{ if .Values.general.enabled }}
            serviceAccountName: infrabox-scheduler
            {{ end }}
            containers:
            {{ include "containers_database" . | indent 12 }}
            -
                name: scheduler
                image: {{ include "image_repository" . }}/scheduler-kubernetes:{{ include "image_tag" . }}
                imagePullPolicy: Always
                env:
                {{ include "env_database" . | indent 16 }}
                {{ include "env_general" . | indent 16 }}
                {{ include "env_version" . | indent 16 }}
                {{ include "env_cluster" . | indent 16 }}
                -
                    name: INFRABOX_KUBERNETES_MASTER_HOST
                    value: "kubernetes.default.svc.cluster.local"
                -
                    name: INFRABOX_KUBERNETES_MASTER_PORT
                    value: "443"
                volumeMounts:
                {{ include "mounts_rsa_private" . | indent 16 }}
            volumes:
                {{ include "volumes_database" . | indent 16 }}
                {{ include "volumes_rsa" . | indent 16 }}
