{{ if .Values.docs.enabled }}
kind: Service
apiVersion: v1
metadata:
    name: infrabox-docs
    namespace: infrabox-system
    labels:
        app: infrabox
        infrabox.net/component: docs
spec:
    selector:
        app: infrabox
        infrabox.net/component: docs
    type: NodePort
    ports:
    -
        protocol: TCP
        port: 8080
        targetPort: 8080
    {{ if .Values.docs.node_port }}
        nodePort: {{ .Values.docs.node_port }}
    {{ end }}
{{ end }}
