apiVersion: apps/v1
kind: Deployment
metadata:
    name: infrabox-cluster-status
    labels:
        app: infrabox-cluster-status
spec:
    replicas: 3
    selector:
        matchLabels:
            app: infrabox-cluster-status
    template:
        metadata:
            labels:
                app: infrabox-cluster-status
        spec:
            terminationGracePeriodSeconds: 0
            containers:
            {{ include "containers_database" . | indent 12 }}
            -
                name: cluster-status
                image: {{ include "image_repository" . }}/cluster-status:{{ include "image_tag" . }}
                env:
                {{ include "env_database" . | indent 16 }}
            volumes:
                {{ include "volumes_database" . | indent 16 }}
