apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: infrabox-controller
    namespace: {{ template "system_namespace" . }}
    labels:
        app: infrabox-controller
spec:
    replicas: 1
    template:
        metadata:
            labels:
                app: infrabox-controller
        spec:
            terminationGracePeriodSeconds: 0
            serviceAccountName: infrabox
            containers:
            -
                name: controller
                image: {{ include "image_repository" . }}/controller:{{ include "image_tag"  . }}
                imagePullPolicy: Always
                env:
                -
                    name: WATCH_NAMESPACE
                    value: {{ template "worker_namespace" . }}
                resources:
                    requests:
                        memory: "256Mi"
                        cpu: "200m"
